#!/usr/bin/env bash
# Prepares the test stack for the end-to-end suite:
#   1. certificates (local CA) if they are missing
#   2. the compose test stack (mysql, php, console bridge, nginx, fixtures)
#   3. the database migrated
#   4. an admin user and one site whose domains cover the fixture hosts
#   5. services/e2e/fixtures/site-key.js with that site's public key
#
# Idempotent: running it again reuses the existing admin and site.
#
# Usage: deploy/docker/scripts/e2e-setup.sh
# Environment: TEST_PROJECT (default analytics-test), E2E_ADMIN_EMAIL,
#              E2E_ADMIN_PASSWORD, E2E_SITE_NAME.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$repo_root"

project="${TEST_PROJECT:-analytics-test}"
admin_email="${E2E_ADMIN_EMAIL:-admin@analytics.test}"
admin_password="${E2E_ADMIN_PASSWORD:-Fixture-Passw0rd-2026}"
site_name="${E2E_SITE_NAME:-e2e}"

dc() {
  docker compose -p "$project" \
    -f deploy/docker/compose.base.yml \
    -f deploy/docker/compose.test.yml "$@"
}

echo "==> Certificates"
[ -f deploy/docker/certs/ca.pem ] || ./deploy/docker/certs/gen-certs.sh >/dev/null

echo "==> Test stack"
DOCKER_UID="${DOCKER_UID:-$(id -u)}" DOCKER_GID="${DOCKER_GID:-$(id -g)}" \
  dc up -d --build mysql php console nginx fixtures

echo "==> Database"
dc exec -T php php bin/analytics migrations:migrate --no-interaction --allow-no-migration

echo "==> Admin user"
# The output is captured before it is searched: `grep -q` closes the pipe as
# soon as it matches, which would make the producing command fail under
# `set -o pipefail`.
users="$(dc exec -T php php bin/analytics user:list)"
if printf '%s\n' "$users" | grep -qF "$admin_email"; then
  echo "${admin_email} already exists"
else
  dc exec -T php sh -c "printf '%s' '${admin_password}' | php bin/analytics user:create-admin --email='${admin_email}' --password-stdin"
fi

echo "==> Site"
sites="$(dc exec -T php php bin/analytics site:list)"
public_key="$(printf '%s\n' "$sites" | grep -oE 'pk_[A-Za-z0-9]{21}' | head -n1 || true)"
if [ -z "$public_key" ]; then
  # *.site.test covers www/app/proxy; other.test stays unregistered on purpose
  # (the suite checks that collect refuses a foreign origin).
  dc exec -T php php bin/analytics site:create \
    --name="$site_name" --domain='*.site.test' --timezone=UTC >/dev/null
  sites="$(dc exec -T php php bin/analytics site:list)"
  public_key="$(printf '%s\n' "$sites" | grep -oE 'pk_[A-Za-z0-9]{21}' | head -n1)"
fi
[ -n "$public_key" ] || { echo "ERROR: could not determine the site public key" >&2; exit 1; }

echo "==> Waiting for https://analytics.test/api/v1/health"
for _ in $(seq 1 30); do
  if dc exec -T nginx wget -q -O - http://127.0.0.1/api/v1/health >/dev/null 2>&1; then
    break
  fi
  sleep 1
done
dc exec -T nginx wget -q -O - http://127.0.0.1/api/v1/health >/dev/null

cat > services/e2e/fixtures/site-key.js <<EOF
// Generated by deploy/docker/scripts/e2e-setup.sh — do not commit.
window.ANALYTICS_PUBLIC_KEY = '${public_key}';
window.ANALYTICS_SERVICE_URL = 'https://analytics.test';
EOF

echo "Public key: ${public_key}"
echo "ANALYTICS_PUBLIC_KEY=${public_key}"
