// Computes CSP sha256 hashes of every inline <script> emitted by `nuxt generate`
// and writes them to the API config so the backend can send a strict CSP.
//
// Usage: node scripts/csp-hashes.mjs [publicDir] [outputFile]
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const publicDir = resolve(process.argv[2] ?? join(root, '.output/public'))
const outputFile = resolve(process.argv[3] ?? join(root, '../api/config/csp.php'))

export function inlineScriptHashes(html) {
  const hashes = []
  const re = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi
  for (const match of html.matchAll(re)) {
    const attrs = match[1]
    const content = match[2]
    if (/\bsrc\s*=/i.test(attrs) || content.length === 0) continue
    hashes.push(`sha256-${createHash('sha256').update(content, 'utf8').digest('base64')}`)
  }
  return hashes
}

export function toPhp(hashes) {
  const lines = hashes.map(h => `        '${h}',`).join('\n')
  return `<?php

declare(strict_types=1);

// Generated by services/dashboard/scripts/csp-hashes.mjs. Do not edit by hand.
return [
    'script_hashes' => [
${lines}
    ],
];
`
}

function main() {
  const files = ['index.html', '200.html'].map(f => join(publicDir, f)).filter(f => existsSync(f))
  if (files.length === 0) {
    console.error(`No index.html or 200.html found in ${publicDir}; run "pnpm generate" first.`)
    process.exit(1)
  }
  const hashes = [...new Set(files.flatMap(f => inlineScriptHashes(readFileSync(f, 'utf8'))))].sort()
  mkdirSync(dirname(outputFile), { recursive: true })
  writeFileSync(outputFile, toPhp(hashes))
  console.log(`Wrote ${hashes.length} script hashes to ${outputFile}`)
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main()
}
