import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { request } from '@playwright/test'

/**
 * Makes sure the stack is reachable and that the fixture sites know which site
 * to report to.
 *
 * The public key is resolved in this order:
 *   1. ANALYTICS_PUBLIC_KEY (what `make test-e2e` passes)
 *   2. fixtures/site-key.js written by deploy/docker/scripts/e2e-setup.sh
 *   3. `docker compose exec php bin/analytics …` when a docker client is
 *      available (running Playwright from the host instead of the container)
 *
 * The suite never creates the admin or the site over HTTP: the first admin
 * exists only through the console, which is exactly what an operator does.
 */
const here = dirname(fileURLToPath(import.meta.url))
const fixtures = resolve(here, 'fixtures')
const keyFile = join(fixtures, 'site-key.js')
const baseURL = process.env.E2E_BASE_URL ?? 'https://analytics.test'
const serviceUrl = process.env.E2E_SERVICE_URL ?? baseURL
const KEY_PATTERN = /pk_[A-Za-z0-9]{21}/
const SITE_NAME = process.env.E2E_SITE_NAME ?? 'e2e'

function fromKeyFile(): string | undefined {
  if (!existsSync(keyFile)) return undefined
  return readFileSync(keyFile, 'utf8').match(KEY_PATTERN)?.[0]
}

function fromDocker(): string | undefined {
  const project = process.env.TEST_PROJECT ?? 'analytics-test'
  const repoRoot = resolve(here, '../..')
  const compose = [
    'compose', '-p', project,
    '-f', 'deploy/docker/compose.base.yml',
    '-f', 'deploy/docker/compose.test.yml',
  ]
  const run = (args: string[]): string =>
    execFileSync('docker', [...compose, ...args], { cwd: repoRoot, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] })

  try {
    run(['exec', '-T', 'php', 'php', 'bin/analytics', 'migrations:migrate', '--no-interaction', '--allow-no-migration'])
    try {
      run(['exec', '-T', 'php', 'sh', '-c',
        `printf '%s' '${process.env.E2E_ADMIN_PASSWORD ?? 'Fixture-Passw0rd-2026'}' | php bin/analytics user:create-admin --email='${process.env.E2E_ADMIN_EMAIL ?? 'admin@analytics.test'}' --password-stdin`])
    } catch {
      // the admin already exists
    }
    // Found by name: the suite creates other sites, and the first one listed need not cover *.site.test.
    const fixtureKey = (): string | undefined => run(['exec', '-T', 'php', 'php', 'bin/analytics', 'site:list'])
      .split('\n').find(line => line.includes(`| ${SITE_NAME} `))?.match(KEY_PATTERN)?.[0]
    let key = fixtureKey()
    if (!key) {
      run(['exec', '-T', 'php', 'php', 'bin/analytics', 'site:create', `--name=${SITE_NAME}`, '--domain=*.site.test', '--timezone=UTC'])
      key = fixtureKey()
    }
    return key
  } catch {
    return undefined
  }
}

export default async function globalSetup(): Promise<void> {
  const publicKey = process.env.ANALYTICS_PUBLIC_KEY?.match(KEY_PATTERN)?.[0] ?? fromKeyFile() ?? fromDocker()
  if (!publicKey) {
    throw new Error(
      'No tracking site available for the e2e run.\n' +
      'Start the stack and create the fixtures site first:\n' +
      '  make e2e-setup\n' +
      '(or export ANALYTICS_PUBLIC_KEY=pk_… for an existing site).',
    )
  }

  writeFileSync(
    keyFile,
    `// Generated by services/e2e/global-setup.ts — do not commit.\n` +
    `window.ANALYTICS_PUBLIC_KEY = '${publicKey}';\n` +
    `window.ANALYTICS_SERVICE_URL = '${serviceUrl}';\n`,
  )
  process.env.ANALYTICS_PUBLIC_KEY = publicKey

  // The service must answer before any test starts.
  const api = await request.newContext({ baseURL, ignoreHTTPSErrors: true })
  const deadline = Date.now() + 60_000
  for (;;) {
    try {
      const response = await api.get('/api/v1/health')
      if (response.ok()) break
    } catch {
      // not up yet
    }
    if (Date.now() > deadline) throw new Error(`${baseURL}/api/v1/health did not answer within 60s`)
    await new Promise(resolve => setTimeout(resolve, 1000))
  }
  await api.dispose()
}
