// Generates src/generated/tracker.ts from the tracker's own source (services/tracker/src/api.ts and
// consent.ts), so the SDK's types are the tracker's types and never a second copy typed by hand.
//
//   node scripts/tracker-types.mjs          write the file
//   node scripts/tracker-types.mjs --check  fail when the committed file differs (CI, and a test)
//
// The SDK ships no tracker code: only these type declarations are taken from the tracker.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tracker = resolve(root, '../../tracker/src');
const target = join(root, 'src/generated/tracker.ts');

/** Named types copied verbatim from the tracker, in this order: [file, exported name, SDK name]. */
const COPIED = [
  ['consent.ts', 'Status', 'ConsentStatus'],
  ['consent.ts', 'ConsentState', 'ConsentState'],
];

export function generate() {
  const program = ts.createProgram([join(tracker, 'api.ts')], {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    lib: ['lib.es2022.d.ts', 'lib.dom.d.ts', 'lib.dom.iterable.d.ts'],
    strict: true,
    noEmit: true,
    types: [],
  });
  const checker = program.getTypeChecker();
  const out = [];

  let renamed = (text) => text;
  for (const [file, name, as] of COPIED) {
    const source = program.getSourceFile(join(tracker, file));
    if (!source) throw new Error(`services/tracker/src/${file} not found`);
    const node = source.statements.find(
      (s) =>
        (ts.isInterfaceDeclaration(s) || ts.isTypeAliasDeclaration(s)) &&
        s.name.text === name &&
        s.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword),
    );
    if (!node) throw new Error(`export ${name} not found in services/tracker/src/${file}`);
    const prev = renamed;
    renamed = (text) => prev(text).replace(new RegExp(`\\b${name}\\b`, 'g'), as);
    out.push({ text: node.getText(source), name, as });
  }

  const api = program.getSourceFile(join(tracker, 'api.ts'));
  const decl = api.statements
    .filter(ts.isVariableStatement)
    .flatMap((s) => s.declarationList.declarations)
    .find((d) => ts.isIdentifier(d.name) && d.name.text === 'api');
  if (!decl) throw new Error('export const api not found in services/tracker/src/api.ts');
  const node = checker.typeToTypeNode(
    checker.getTypeAtLocation(decl.name),
    undefined,
    ts.NodeBuilderFlags.NoTruncation | ts.NodeBuilderFlags.UseAliasDefinedOutsideCurrentScope,
  );
  const multiline = (n) => {
    ts.setEmitFlags(n, ts.EmitFlags.None);
    ts.forEachChild(n, multiline);
  };
  multiline(node);
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  const apiType = printer
    .printNode(ts.EmitHint.Unspecified, node, api)
    .replace(/^( +)/gm, (s) => s.slice(0, s.length / 2))
    .replace(/ \| undefined/g, '');

  const known = new Set(['Record', 'string', 'number', 'boolean', 'unknown', 'void', 'null', 'undefined', ...COPIED.map((c) => c[1])]);
  for (const id of apiType.match(/\b[A-Z][A-Za-z0-9_]*\b/g) ?? []) {
    if (!known.has(id)) {
      throw new Error(`The tracker's api type refers to ${id}: add it to COPIED in scripts/tracker-types.mjs`);
    }
  }

  const lines = [
    '// Generated by scripts/tracker-types.mjs from services/tracker/src/api.ts and consent.ts.',
    '// Do not edit: run `pnpm tracker-types` after changing the tracker API.',
    '/* eslint-disable */',
    '',
    ...out.flatMap(({ text }) => [renamed(text), '']),
    '/** The tracker API object installed as `window.analytics` (or the configured global name). */',
    `export type TrackerApi = ${renamed(apiType)};`,
    '',
  ];
  return lines.join('\n');
}

const check = process.argv.includes('--check');
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const fresh = generate();
  if (check) {
    let current = '';
    try {
      current = readFileSync(target, 'utf8');
    } catch {
      // missing counts as stale
    }
    if (fresh !== current) {
      console.error('src/generated/tracker.ts is out of date. Run "pnpm tracker-types" and commit the result.');
      process.exit(1);
    }
    console.log('src/generated/tracker.ts is up to date.');
  } else {
    writeFileSync(target, fresh);
    console.log('wrote src/generated/tracker.ts');
  }
}
