// Generates src/generated/openapi.ts from the `/server/*` paths of docs/api/openapi.yaml with
// openapi-typescript (as the dashboard does for the whole document with `pnpm openapi-types`).
// Only the server paths and the components they reference are kept, so dashboard-only changes to
// the document never make this file stale.
//
//   node scripts/openapi-types.mjs          write the file
//   node scripts/openapi-types.mjs --check  fail when the committed file differs (CI)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import { parse } from 'yaml';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = resolve(root, '../../../docs/api/openapi.yaml');
const target = join(root, 'src/generated/openapi.ts');

/** The document with only `/server/*` paths and the components reachable from them. */
export function serverDocument(doc) {
  const paths = Object.fromEntries(Object.entries(doc.paths).filter(([p]) => p.startsWith('/server/')));
  const keep = new Map();
  const visit = (node) => {
    if (Array.isArray(node)) return node.forEach(visit);
    if (!node || typeof node != 'object') return;
    for (const [k, v] of Object.entries(node)) {
      if (k == '$ref' && typeof v == 'string') {
        const m = /^#\/components\/([^/]+)\/([^/]+)$/.exec(v);
        if (!m) throw new Error(`unsupported $ref ${v}`);
        const key = `${m[1]}/${m[2]}`;
        if (!keep.has(key)) {
          const target = doc.components?.[m[1]]?.[m[2]];
          if (!target) throw new Error(`dangling $ref ${v}`);
          keep.set(key, target);
          visit(target);
        }
      } else visit(v);
    }
  };
  visit(paths);
  const components = {};
  for (const [key, value] of [...keep].sort(([a], [b]) => a.localeCompare(b))) {
    const [kind, name] = key.split('/');
    (components[kind] ??= {})[name] = value;
  }
  // Security schemes are referenced by name, not by $ref.
  if (doc.components?.securitySchemes?.apiKey) {
    components.securitySchemes = { apiKey: doc.components.securitySchemes.apiKey };
  }
  return { openapi: doc.openapi, info: doc.info, servers: doc.servers, paths, components };
}

export async function generate() {
  // Aliases (&reportParams / *reportParams) become plain copies.
  const doc = parse(readFileSync(source, 'utf8'), { maxAliasCount: -1 });
  const ast = await openapiTS(serverDocument(doc), { alphabetize: false });
  return [
    '// Generated by scripts/openapi-types.mjs from the /server/* paths of docs/api/openapi.yaml.',
    '// Do not edit: run `pnpm openapi-types` after changing the API document.',
    '/* eslint-disable */',
    '',
    astToString(ast),
  ].join('\n');
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const fresh = await generate();
  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(target, 'utf8');
    } catch {
      // missing counts as stale
    }
    if (fresh !== current) {
      console.error('src/generated/openapi.ts is out of date. Run "pnpm openapi-types" and commit the result.');
      process.exit(1);
    }
    console.log('src/generated/openapi.ts is up to date.');
  } else {
    writeFileSync(target, fresh);
    console.log('wrote src/generated/openapi.ts');
  }
}
